replicaCount: 3

image:
  tag: "1.0.0"

resources:
  requests:
    memory: 256Mi
    cpu: 200m

  limits:
    memory: 512Mi
    cpu: 400m

config:
  logLevel: info 

ingress:
  enabled: true
  host: "helmstore.microservice.com"